### ISSUE TITLE
GUYS ZOOM TOPLANTI

### ISSUE THREAD

**Issue by benguyurdakul** [dorukbulut/deneme_algo_projesi#4]
**Zoom toplantı linki ;**
Bengü Yurdakul is inviting you to a scheduled Zoom meeting.

Topic: Bengü Yurdakul's Zoom Meeting
Time: Apr 27, 2021 09:00 PM Istanbul

Join Zoom Meeting
https://us04web.zoom.us/j/4420647160?pwd=dW9aLy83ZDlZZ2FlTUFKNldLT0F4UT09

Meeting ID: 442 064 7160
Passcode: bengu

**Eglenmek icin issue yaptım**

**Comment by dorukbulut** [comment]
no tatava yes baklava
